### PR TITLE
Merge options passed into all methods

### PR DESCRIPTION
**Pull request by shioyama**
Continued from #16, based on suggestion from @kuruga.

### CODE REVIEW

**Comment by shioyama** [comment]
@jackdempsey What do you think about this change? I agree with @kuraga that this makes more sense.

Also, it would be great if a new version could be released so projects that depend on this feature can check that it is available.

**Comment by jackdempsey** [comment]
I think that looks fine, just gotta be careful about keys showing up that will conflict with calls unexpectedly. 

I don't use this code these days but am happy to give you/others access so you can release and make things better for yourself and others. Let me know!

**Comment by kuraga** [comment]
@shioyama I'll make a release soon.

**Comment by shioyama** [comment]
@kuraga Thanks!

**Comment by kuraga** [comment]
@jackdempsey push new version to RubyGems, please

**Pull request merged**
