### PR TITLE
Add a .where that searches on polymorphic ids and types

### LINKED ISSUE #24: .where on polymorphic ass.
Hi @kuraga and @jackdempsey,
Is it true you can't run, i.e.:

Episode.where(media: Project.first)

As it returns:
```
NameError: uninitialized constant Media (this happened when attempting to find the associated class for #<Sequel::Model::Associations::ManyToOneAssociationReflection Episode.many_to_one :media, :reciprocal=>:episodes, :reciprocal_type=>:many_to_one, :setter=>#<Proc:0x00000004dae1a8@/home/vagrant/.rvm/gems/ruby-2.3.3/bundler/gems/sequel_polymorphic-ea47ba8eef73/lib/sequel/plugins/polymorphic.rb:28>, :dataset=>#<Proc:0x00000004dae180@/home/vagrant/.rvm/gems/ruby-2.3.3/bundler/gems/sequel_polymorphic-ea47ba8eef73/lib/sequel/plugins/polymorphic.rb:32>, :eager_loader=>#<Proc:0x00000004dae158@/home/vagrant/.rvm/gems/ruby-2.3.3/bundler/gems/sequel_polymorphic-ea47ba8eef73/lib/sequel/plugins/polymorphic.rb:39>, :polymorphic=>true>)
from /home/vagrant/.rvm/gems/ruby-2.3.3/gems/activesupport-5.1.3/lib/active_support/inflector/methods.rb:269:in `const_get'
```

Do you have any idea to inject this into .where rather than creating a .polymorphic_where function?

### PR DESCRIPTION
**Pull request by jnylen**
You can pretty much do

```ruby
@post = Post.create(:name => 'test post')
@asset1 = Asset.create(:name => "post's first asset", attachable: @post)
@asset1.save
@post.refresh

Asset.where(attachable: @post)
```

Similar to AR.

Closes #24

### CODE REVIEW

**Comment by jnylen** [comment]
Don't merge yet.

**Comment by jnylen** [comment]
@kuraga,
This should work fine.

Basicially it will replace any <assoc>: <model> with _type and _id.

**Comment by jnylen** [comment]
@kuraga, @jackdempsey:
Any idea if you want this implemented or not? It's quite good thing to have.

**Comment by kuraga** [comment]
@jnylen , I don't use `sequel_polymorphic` anymore (and Ruby, and web-programming :smile: ) but I like your patch.

1) What about `#where` for other associations?

2) What about  fallback test (i.e. non-polymorphic `#where` call)?

**Comment by jnylen** [comment]
@kuraga,
Ah, alrighty.

1. Do you mean non-polymorphic? If so, they still work. The where call just checks if the model its called on and the corresponding assoc. is a polymorphic assoc.
2. I can add that if you want. It does work though.

**Comment by jnylen** [comment]
Added some tests, these pass aswell on 4.49.

**Comment by kuraga** [comment]
@jnylen 
1. No, polymorphic `#where` for other associations.
2. Yes, please. I can but later.

**Comment by jnylen** [comment]
@kuraga,
1. I'll fix that a bit later today/tomorrow/this week.
2. Added some tests for the one that already has one. I'll add similar ones for the other assocs.

**Comment by jnylen** [comment]
@kuraga,
This should be fine now. Not sure about the .where specs in many_to_one though.

The specs returns with: `30 runs, 39 assertions, 0 failures, 0 errors, 0 skips`

**Comment by kuraga** [comment]
@jnylen would you become a maintainer? :smile:

**Comment by kuraga** [comment]
@jnylen , I'm serious!

Because of: I don't use web programming anymore and #20 .

**Comment by jnylen** [comment]
@kuraga,
Sorry for no answer, I don't know. I'm busy in real life. But I can try to fix things when they break as I will use Sequel in the new backend.

So in short. Sure.

But wouldn't it be better if @jeremyevans made it an official plugin?

**Comment by jeremyevans** [comment]
I won't consider this as an official plugin as I don't want to encourage the use of polymorphic associations and don't want to maintain it.

**Comment by jnylen** [comment]
Alright jeremy,

@kuraga, then I can be a maintainer. ;)

**Comment by kuraga** [comment]
@jnylen ok, will do this weekend.

**Comment by jackdempsey** [comment]
Thanks for the headsup @kuraga. 

@jnylen you are now a contributor here and owner on rubygems.org.

**Comment by kuraga** [comment]
@jnylen , ping

**Comment by jnylen** [comment]
@kuraga,
Yes, saw it. I'll take a look a bit later. Busy right now. ;)

**Comment by rodrigopinto** [comment]
Hi @jnylen, nice work here, really thanks! 👏 👏 👏 

I was wondering what do we need to get it merged. Do you have a plan to release it soon?

**Comment by jnylen** [comment]
Hi @rodrigopinto,

I don't really use ruby that much as I moved to Elixir (due to most frameworks being heavy or slow).
You should be able to use that github repo though. Try it out and get back to me if it doesn't work or not.

**Comment by kuraga** [comment]
I'm back :smile: Merged, thanks to all!

**Pull request closed without merging**
