### PR TITLE
Handle class option to one-to-many association

### PR DESCRIPTION
**Pull request by shioyama**
This is quite a simple change and allows more flexible association/class name relationships.

### CODE REVIEW

**Comment by jackdempsey** [comment]
@shioyama Seems we should pass klass along if someone passes in a value. Update that and i'm fine with merging it.

**Comment by shioyama** [comment]
@jackdempsey I had that at first, but noticed no difference and this was simpler so just passed it as nil by default. But I'll make the change if you think that's better.

**Comment by jackdempsey** [comment]
Yeah, even if it works now, something may change and break in the future, etc. This should make it more bulletproof. Thanks!

**Comment by shioyama** [comment]
Ok updated, have a look :smile:

**Comment by jackdempsey** [comment]
Thanks!

**Comment by kuraga** [comment]
@shioyama @jackdempsey 
what about handling _all_ options but not `:class` only?
```ruby
association_options = { ... }.merge(options)
```
(in all methods)

**Comment by shioyama** [comment]
@kuraga Good point, I was only thinking about my immediate need. Would there be any issue with passing through options, i.e. could they affect polymorphic associations in a way that would break them? I guess not but I'm new to Sequel.

I can make another PR with the `merge(options)` approach.

**Comment by kuraga** [comment]
@shioyama we couldn't, user (programmer) could. But that's user's decision (give some `options`).

**Pull request merged**
